### ISSUE TITLE
Handle "User not found" error

### ISSUE THREAD

**Issue by simonw** [dogsheep/twitter-to-sqlite#37]
While running `user-timeline` I got this bug (because a screen name I asked for didn't exist):
```
  File "/Users/simonw/Dropbox/Development/twitter-to-sqlite/twitter_to_sqlite/utils.py", line 185, in transform_user
    user["created_at"] = parser.parse(user["created_at"])
KeyError: 'created_at'
>>> import pdb
>>> pdb.pm()
> /Users/simonw/Dropbox/Development/twitter-to-sqlite/twitter_to_sqlite/utils.py(185)transform_user()
-> user["created_at"] = parser.parse(user["created_at"])
(Pdb) user
{'errors': [{'code': 50, 'message': 'User not found.'}]}
```

**Comment by simonw** [comment]
```
$ twitter-to-sqlite user-timeline doggo.db doggoenthuonetuh
Traceback (most recent call last):
...
  File "/Users/simonw/Dropbox/Development/twitter-to-sqlite/twitter_to_sqlite/utils.py", line 272, in transform_user
    user["created_at"] = parser.parse(user["created_at"])
KeyError: 'created_at'
```

**Comment by simonw** [comment]
I'm going to print a warning to stderr, skip and continue - because if you have 100 screen names and only one of them is invalid you should still execute for the other 99.

**Comment by simonw** [comment]
That's a bit tricky since I'd have to rewrite the internals of a bunch of other commands. For the moment I'll exit the script with an error but at least it will be a decent error!
