### ISSUE TITLE
Error: Use either --since or --since_id, not both

### ISSUE THREAD

**Issue by rubenv** [dogsheep/twitter-to-sqlite#57]
I'm using the following command:

```
twitter-to-sqlite user-timeline -a twitter-auth.json twitter/tweets.db --since
```

Which gives the following error:
```
Error: Use either --since or --since_id, not both
```

Running without `--since`.

```
Traceback (most recent call last):
  File "/usr/local/bin/twitter-to-sqlite", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/twitter_to_sqlite/cli.py", line 317, in user_timeline
    for tweet in bar:
  File "/usr/local/lib/python3.9/site-packages/click/_termui_impl.py", line 328, in generator
    for rv in self.iter:
  File "/usr/local/lib/python3.9/site-packages/twitter_to_sqlite/utils.py", line 234, in fetch_user_timeline
    yield from fetch_timeline(
  File "/usr/local/lib/python3.9/site-packages/twitter_to_sqlite/utils.py", line 202, in fetch_timeline
    raise Exception(str(tweets["errors"]))
Exception: [{'code': 44, 'message': 'since_id parameter is invalid.'}]
```

```
Python 3.9.5
twitter-to-sqlite, version 0.21.3
```

**Comment by stiles** [comment]
I'm having the same issue (same versions of python and twitter-to-sqlite). It's the `user-timeline` command. Other commands are working.

**Comment by simonw** [comment]
I'm getting this too. Looking into it now.

**Comment by simonw** [comment]
https://developer.twitter.com/en/docs/twitter-api/v1/tweets/timelines/api-reference/get-statuses-user_timeline says the API has been replaced by the new v2 one, but it should still work - and the `since_id` parameter is still documented on that page.

**Comment by simonw** [comment]
Weird, added debug code and got this: `{'screen_name': 'simonw', 'count': 200, 'since_id': 'False', 'tweet_mode': 'extended'}` -  so maybe it's a `twitter-to-sqlite` bug where somehow the string `False` is being passed somewhere.

**Comment by simonw** [comment]
This looks like the bug to me:

https://github.com/dogsheep/twitter-to-sqlite/blob/197e69cec40052c423a5ed071feb5f7cccea41b9/twitter_to_sqlite/cli.py#L239-L241

`type=str, default=False`

**Comment by simonw** [comment]
Maybe Click changed something which meant that this broke things when it didn't used to?
