### ISSUE TITLE
KeyError: 'created_at' for private accounts?

### ISSUE THREAD

**Issue by sw-yx** [dogsheep/twitter-to-sqlite#62]
hey Simon!

i was running `twitter-to-sqlite user-timeline twitter.db` for [my private alt](https://twitter.com/swyxio) and ran into this error:

<details>
<summary>

![image](https://user-images.githubusercontent.com/6764957/147416165-46b69c30-100a-406f-8534-8612b75547ae.png)

</summary>

```bash
Traceback (most recent call last):
  File "/Users/swyx/Work/datasette/env/bin/twitter-to-sqlite", line 8, in <module>
    sys.exit(cli())
  File "/Users/swyx/Work/datasette/env/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/swyx/Work/datasette/env/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/swyx/Work/datasette/env/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/swyx/Work/datasette/env/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/swyx/Work/datasette/env/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/swyx/Work/datasette/env/lib/python3.9/site-packages/twitter_to_sqlite/cli.py", line 291, in user_timeline
    profile = utils.get_profile(db, session, **kwargs)
  File "/Users/swyx/Work/datasette/env/lib/python3.9/site-packages/twitter_to_sqlite/utils.py", line 133, in get_profile
    save_users(db, [profile])
  File "/Users/swyx/Work/datasette/env/lib/python3.9/site-packages/twitter_to_sqlite/utils.py", line 453, in save_users
    transform_user(user)
  File "/Users/swyx/Work/datasette/env/lib/python3.9/site-packages/twitter_to_sqlite/utils.py", line 285, in transform_user
    user["created_at"] = parser.parse(user["created_at"])
KeyError: 'created_at'
```

</details>

this looks awfully like #37  but it can't be, because i'm authed into my account and obviously i have perms to read my own account. wonder if there's any diagnostic methods i should apply here? just filing an issue for others to find while i investigate.

**Comment by sw-yx** [comment]
just confirmed that this error does not occur when i use my public main account. gets more interesting!

**Comment by miuku** [comment]
i seem to have fixed this issue by applying for [elevated API access](https://developer.twitter.com/en/portal/products/elevated)

**Comment by swyxio** [comment]
gonna close this for now since i'm not actively working on it.
